### ISSUE TITLE
Not found dependency while installing with pip

### ISSUE THREAD

**Issue by mesand** [ARMmbed/icetea#101]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug |  Question

---------------------------------------------------------------
## Bug

**Icetea version**
2.0.0

**Expected Behavior**
install normally with pip
**Actual Behavior**
Could not find a version that satisfies the requirement trollius==1.0.4 (from pyshark-legacy->icetea) (from versions: 2.1.post2, 2.2, 2.2.post1)
No matching distribution found for trollius==1.0.4 (from pyshark-legacy->icetea)

**Steps to Reproduce**
"pip install icetea" on a clean machine
----------------------------------------------------------------

## Question

**How to solve this error message?**

**Comment by muchzill4** [comment]
https://github.com/vstinner/trollius/issues/16

**Comment by jonikula** [comment]
This should be resolved by new trollius versions becoming available again.

**Comment by jonikula** [comment]
Dependency should now be removed from 1.2.X branch with release of v1.2.4.

**Comment by jonikula** [comment]
Should be resolved now with versions v1.2.4 and v2.0.1
