### ISSUE TITLE
jsonschema version

### ISSUE THREAD

**Issue by jprodriguez-nbs** [ARMmbed/icetea#113]
- Type: Enhancement
- Version: icetea 2.0.1
- Problem: requires jsonschema<3.0.0; Version 2.6.0 is from 2017
- Request: update to use >=3.2.0
- Pros: Easier environment setup by avoiding incompatibilities

**Comment by 0xc0170** [comment]
This repository is no longer maintained and it is deprecated. As result, we are closing all issues/pull request.
