### ISSUE TITLE
icetea 2.0.1 depends on prettytable<1.0

### ISSUE THREAD

**Issue by jprodriguez-nbs** [ARMmbed/icetea#114]
- Type: Enhancement
- Version: icetea 2.0.1
- Reason: icetea 2.0.1 depends on prettytable<1.0. Version 0.7.2 is from 2013
- Enhancement: Update to use prettytable 2.0
- Pros: Easy environment, avoid dependency incompatibilities.

**Comment by Patater** [comment]
We can try `prettytable<3.0,>=2.0; python_version >= "3.6"'` to keep python 2 compatibility and still allow a modern python 3 set up to work.

**Comment by 0xc0170** [comment]
This repository is no longer maintained and it is deprecated. As result, we are closing all issues/pull request.
