### ISSUE TITLE
Icetea does not list `jsonschema` as a requirement

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/icetea#36]
### Description
- Type: Bug

---------------------------------------------------------------
## Bug

Icetea does not list `jsonschema` as a requirement, but still depends on it.

**Comment by jonikula** [comment]
Icetea itself does not directly use jsonschema. Jsonmerge uses jsonschema and Icetea depends on jsonmerge.

**Comment by jupe** [comment]
Fixed by https://github.com/ARMmbed/icetea/pull/41
