### ISSUE TITLE
Better error message when not enough devices connected

### ISSUE THREAD

**Issue by OPpuolitaival** [ARMmbed/icetea#39]
### Description
Now "No suitable local device available" reported when need more devices and not found enough. 

Expected something like: "1/2 suitable devices found" that it is more clear for user to add more devices

Original issue: https://github.com/ARMmbed/mbed-os/issues/8028

**Comment by jonikula** [comment]
This PR should improve the situation here slightly: https://github.com/ARMmbed/icetea/pull/42

**Comment by jupe** [comment]
Fix will included in next release
