### ISSUE TITLE
Version pinning in *requirements.txt files

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/icetea#69]
### Description
- Type: Bug | Enhancement
- Related Issue: https://github.com/mbedmicro/pyOCD/pull/511, 

## Enhancement

In leiu of recent ARMmbed/mbed-os struggles, I'd _strongly_ suggesting that `icetea` version pin their python modules, found in these three files:
- https://github.com/ARMmbed/icetea/blob/master/requirements.txt
- https://github.com/ARMmbed/icetea/blob/master/dev_requirements.txt
- https://github.com/ARMmbed/icetea/blob/master/extra_requirements.txt

**Reason to enhance/problem with existing solution**
Version numbers increase CI stability by preventlng a stray module update from halting testing in the repo.

**Comment by bridadan** [comment]
At least pinning the major version would help with stability quite a bit!

**Comment by jupe** [comment]
yep, major versio pinning should be enough as long as dependencies follow semantic version rules

**Comment by jonikula** [comment]
I'll plug this into the next patch.

**Comment by cmonr** [comment]
> as long as dependencies follow semantic version rules

That's always the dream

**Comment by jonikula** [comment]
PR merged.
