### ISSUE TITLE
ICETEA: DEFAULT TEST CASES ARE FAILING ON NUCLEO_F429ZI

### ISSUE THREAD

**Issue by abhi227** [ARMmbed/icetea#98]
Facing multiple fails for test cases under TEST_APPS directory, my setup involves

DUT'S : NUCLEO_F429ZI x 2
TEST ALGORITH: ICE TEA

compiling using mbed cli interface with GCC_ARM. Please refer to attached logs for further info, looking for your valuable suggestion. 

abhi

**Comment by 0xc0170** [comment]
This repository is no longer maintained and it is deprecated. As result, we are closing all issues/pull request.
